projects:
  ChatMessenger:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: chatmessenger
        docsFilePath: .
        region: us-east-1
        apiId: r6uv3tprwresrba4imn32qjrw4
        maxDepth: 2
extensions:
  amplify:
    version: 3
